// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:budgetpie/models/expense.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(ExpenseCategoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(ExpenseCategoryAdapter());
  }
}
